/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointerdisciplinar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Richa
 */
public class Consulta extends javax.swing.JFrame {
      private String placa, marca, modelo,Estado,Loja;
    private String Ano;
    private String date;
    private float preco;
    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Placa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 21, 40, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 10, 100, 30);

        jButton1.setText("Consulta Placa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 10, 120, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 226, 306, 115);

        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 87, 50, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 90, 100, 30);

        jLabel3.setText("Modelo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 56, 50, 14);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(80, 50, 100, 30);

        jLabel4.setText("Preço 1: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 152, 50, 14);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(70, 150, 97, 30);

        jLabel5.setText("Preço 2:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 150, 50, 14);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 150, 97, 30);

        jLabel6.setText("Pesquisa por Faixa de Preço: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 120, 210, 23);

        jButton2.setText("Consulta Marca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 100, 130, 23);

        jButton3.setText("Consulta Modelo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 60, 150, 23);

        jButton4.setText("Consultar por Faixa de Preço");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(88, 187, 210, 23);

        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(350, 230, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          //Botão 'Mostrar professores':
        Connection con = null;
        Statement statement = null;
        ResultSet results = null;
        java.text.DecimalFormat fmt = new java.text.DecimalFormat("0.00");
        float soma = 0.0f;
        int q = 0;
        String  str = "";
        try {
            Class.forName("com.mysql.jdbc.Driver"); 
            //A seguir reparamos a url para conexão com o banco de dados 'universidademysql':
            String url = "jdbc:mysql://localhost/projeto" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; 
            con = DriverManager.getConnection(url,"root", ""); 
            statement = con.createStatement();
            placa = jTextField1.getText();
            String query = "SELECT * FROM veiculos WHERE placa = '"+placa+"'";
            results = statement.executeQuery(query);        
            while (results.next())  {
               placa = results.getString("placa");
               modelo =  results.getString("modelo");
               marca = results.getString("marca");
               preco = results.getFloat("preco");
              
            
              str += "Placa: "+placa+ " - Modelo: " + modelo  
                      + " -  Marca: " +marca+ " - Preço: " +preco+ "\n";
            }
                      
        }
        catch (SQLException e1) {
            str = "Erro no processamento do BD. " + e1.getMessage();
        }
        catch (Exception e2) {
            str = "Erro no processamento do BD. " + e2.getMessage();
        }
        finally {
            jTextArea1.setText(str);
            try { 
              if(results!=null){results.close(); results=null;}
              if(statement!=null){statement.close(); statement=null;}
              if(con!=null){con.close(); con=null;}
            }
            catch (Exception e3) {}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con = null;
        Statement statement = null;
        ResultSet results = null;
        java.text.DecimalFormat fmt = new java.text.DecimalFormat("0.00");
        float soma = 0.0f;
        int q = 0;
        String  str = "";
        try {
            Class.forName("com.mysql.jdbc.Driver"); 
            //A seguir reparamos a url para conexão com o banco de dados 'universidademysql':
            String url = "jdbc:mysql://localhost/projeto" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; 
            con = DriverManager.getConnection(url,"root", ""); 
            statement = con.createStatement();
            marca = jTextField2.getText();
            String query = "SELECT * FROM veiculos WHERE marca = '"+marca+"'";
            results = statement.executeQuery(query);        
            while (results.next())  {
               placa = results.getString("placa");
               modelo =  results.getString("modelo");
               marca = results.getString("marca");
               preco = results.getFloat("preco");
               Ano = results.getString("ano");
               Loja = results.getString("loja");
               Estado = results.getString("estado");
               
              
            
              str += "Placa: "+placa+ " - Modelo: " + modelo  
                      + " -  Marca: " +marca+ " - Preço: "+preco+ " - Ano "+Ano+" - Loja: "+Loja+" - Estado: "+Estado+"\n";
            }
                      
        }
        catch (SQLException e1) {
            str = "Erro no processamento do BD. " + e1.getMessage();
        }
        catch (Exception e2) {
            str = "Erro no processamento do BD. " + e2.getMessage();
        }
        finally {
            jTextArea1.setText(str);
            try { 
              if(results!=null){results.close(); results=null;}
              if(statement!=null){statement.close(); statement=null;}
              if(con!=null){con.close(); con=null;}
            }
            catch (Exception e3) {}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con = null;
        Statement statement = null;
        ResultSet results = null;
        java.text.DecimalFormat fmt = new java.text.DecimalFormat("0.00");
        float soma = 0.0f;
        int q = 0;
        String  str = "";
        try {
            Class.forName("com.mysql.jdbc.Driver"); 
            //A seguir reparamos a url para conexão com o banco de dados 'universidademysql':
            String url = "jdbc:mysql://localhost/projeto" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; 
            con = DriverManager.getConnection(url,"root", ""); 
            statement = con.createStatement();
            modelo = jTextField3.getText();
            String query = "SELECT * FROM veiculos WHERE modelo = '"+modelo+"'";
            results = statement.executeQuery(query);        
            while (results.next())  {
               placa = results.getString("placa");
               modelo =  results.getString("modelo");
               marca = results.getString("marca");
               preco = results.getFloat("preco");
               Ano = results.getString("ano");
               Loja = results.getString("loja");
               Estado = results.getString("estado");
               
              
            
              str += "Placa: "+placa+ " - Modelo: " + modelo  
                      + " -  Marca: " +marca+ " - Preço: "+preco+ " - Ano "+Ano+" - Loja: "+Loja+" - Estado: "+Estado+"\n";
            }
                      
        }
        catch (SQLException e1) {
            str = "Erro no processamento do BD. " + e1.getMessage();
        }
        catch (Exception e2) {
            str = "Erro no processamento do BD. " + e2.getMessage();
        }
        finally {
            jTextArea1.setText(str);
            try { 
              if(results!=null){results.close(); results=null;}
              if(statement!=null){statement.close(); statement=null;}
              if(con!=null){con.close(); con=null;}
            }
            catch (Exception e3) {}
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con = null;
        Statement statement = null;
        ResultSet results = null;
        java.text.DecimalFormat fmt = new java.text.DecimalFormat("0.00");
        float soma = 0.0f;
        int q = 0;
        String  str = "";
        try {
            Class.forName("com.mysql.jdbc.Driver"); 
            //A seguir reparamos a url para conexão com o banco de dados 'universidademysql':
            String url = "jdbc:mysql://localhost/projeto" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; 
            con = DriverManager.getConnection(url,"root", ""); 
            statement = con.createStatement();
            float prec1 = Float.parseFloat(jTextField4.getText());
            float prec2 = Float.parseFloat(jTextField5.getText());
            String query = "SELECT * FROM veiculos WHERE preco >= '"+prec1+"' AND preco <= '"+prec2+"'";
            results = statement.executeQuery(query);        
            while (results.next())  {
               placa = results.getString("placa");
               modelo =  results.getString("modelo");
               marca = results.getString("marca");
               preco = results.getFloat("preco");
               Ano = results.getString("ano");
               Loja = results.getString("loja");
               Estado = results.getString("estado");
               
              
            
              str += "Placa: "+placa+ " - Modelo: " + modelo  
                      + " -  Marca: " +marca+ " - Preço: "+preco+ " - Ano "+Ano+" - Loja: "+Loja+" - Estado: "+Estado+"\n";
            }
                      
        }
        catch (SQLException e1) {
            str = "Erro no processamento do BD. " + e1.getMessage();
        }
        catch (Exception e2) {
            str = "Erro no processamento do BD. " + e2.getMessage();
        }
        finally {
            jTextArea1.setText(str);
            try { 
              if(results!=null){results.close(); results=null;}
              if(statement!=null){statement.close(); statement=null;}
              if(con!=null){con.close(); con=null;}
            }
            catch (Exception e3) {}
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
