/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointerdisciplinar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Richa
 */
public class MarcasModelos extends javax.swing.JFrame {

    /**
     * Creates new form MarcasModelos
     */
    public MarcasModelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("(Não insira um valor Existente(somente marca) :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 64, 256, 25);

        jLabel2.setText("Modelo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(207, 17, 49, 34);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(64, 17, 125, 34);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 17, 112, 34);

        jButton1.setText("Cadastra somente Marca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 65, 166, 23);

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 150, 178, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 167, 166, 96);

        jLabel3.setText("Marca: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 22, 36, 25);

        jButton5.setText("Cadastra Marca-Modelo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(230, 108, 178, 23);

        jLabel4.setText("(insira um valor Existente) para Marca:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 107, 226, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = null;
        Statement pstm = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");  
            String url = "jdbc:mysql://localhost/projeto" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; 
            con = DriverManager.getConnection(url,"root", ""); 
            pstm = con.createStatement();
           String marca = jTextField1.getText();
           
            String query = "INSERT INTO marcas (nomemarca) VALUES ('"+marca+"')";
                    
            pstm = con.prepareStatement(query);
            
            int res = pstm.executeUpdate(query);     
            if(res > 0)jTextArea1.setText("Marca  Inserida Com Sucesso"); else jTextArea1.setText("O marca não foi inserido"); 
        }
        catch (Exception e1) {
            jTextArea1.setText("Erro inserindo na tabela 'marcas': " + e1.getMessage());
        }
        finally {
            try {         
              if(pstm!=null){pstm.close(); pstm=null;}
              if(con!=null){con.close(); con=null;}
            }
            catch (Exception e2) {}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           Connection con = null;
        Statement pstm = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");  
            String url = "jdbc:mysql://localhost/projeto" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; 
            con = DriverManager.getConnection(url,"root", ""); 
            pstm = con.createStatement();
           String marca = jTextField1.getText();
           String modelo = jTextField2.getText();
           
            String query = "INSERT INTO modelos (nomemarca,nomemodelo) VALUES ('"+marca+"','"+modelo+"')";
                    
            pstm = con.prepareStatement(query);
            
            int res = pstm.executeUpdate(query);     
            if(res > 0)jTextArea1.setText("Marca e Modelo  Inserida Com Sucesso"); else jTextArea1.setText("O marca/modelo não foi inserido"); 
        }
        catch (Exception e1) {
            jTextArea1.setText("Erro inserindo na tabela 'modelos': " + e1.getMessage());
        }
        finally {
            try {         
              if(pstm!=null){pstm.close(); pstm=null;}
              if(con!=null){con.close(); con=null;}
            }
            catch (Exception e2) {}
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcasModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcasModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcasModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcasModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcasModelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
